//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY : Helper.BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.CATEGORY1 = new HashSet<CATEGORY>();
            this.CATEGORY11 = new HashSet<CATEGORY>();
            this.PRODUCTs = new HashSet<PRODUCT>();
            this.SPECIFICATION_TYPE = new HashSet<SPECIFICATION_TYPE>();
            this.DETAIL_REPORT_CATEGORY = new HashSet<DETAIL_REPORT_CATEGORY>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> parentCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORY1 { get; set; }
        public virtual CATEGORY CATEGORY2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORY11 { get; set; }
        public virtual CATEGORY CATEGORY3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIFICATION_TYPE> SPECIFICATION_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_REPORT_CATEGORY> DETAIL_REPORT_CATEGORY { get; set; }
    }
}
