//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_BILL_SERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM_BILL_SERI()
        {
            this.BILL_REPAIR = new HashSet<BILL_REPAIR>();
        }
    
        public int id { get; set; }
        public int billId { get; set; }
        public int productId { get; set; }
        public string seri { get; set; }
    
        public virtual BILL BILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_REPAIR> BILL_REPAIR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
