//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIFICATION : HelperService.BaseViewModel
    {
        public int productId { get; set; }
        public int specificationTypeId { get; set; }
        public string value { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SPECIFICATION_TYPE SPECIFICATION_TYPE { get; set; }
    }
}
